### ISSUE TITLE
wrong number of arguments (given 2, expected 1) in #url

### ISSUE THREAD

**Issue by ndbroadbent** [janko-m/shrine-fog#1]
in `shrine-fog (1.0.0) lib/shrine/storage/fog.rb` line 39: 

```ruby
signed_url = file(id).url(Time.now + @expires, **options)
```

In `fog-google (0.6.0) lib/fog/storage/google_xml/models/file.rb` line 130:

```ruby
        def url(expires)
          requires :key
          collection.get_http_url(key, expires)
        end
```

Looks like the `url` method doesn't take options any more.

UPDATE: Same problem in `fog-google` version `1.3.3`

**Comment by ndbroadbent** [comment]
Which version of `fog-google` would you recommend using? Or would it be better to use https://github.com/renchap/shrine-google_cloud_storage?

**Comment by janko** [comment]
> Which version of fog-google would you recommend using? Or would it be better to use https://github.com/renchap/shrine-google_cloud_storage?

I'm not sure, I never used Google Cloud Storage. I would expect that shrine-google_cloud_storage would be a better bet, as it uses the official google-cloud-storage gem (just like I would recommend aws-sdk-s3 over fog-aws), but I never had any experience with fog-google.
